// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPCkINgcvMZ452-DDemATSz6RhJC-9w4c',
    appId: '1:650378069562:web:061b76f56b546e763f1703',
    messagingSenderId: '650378069562',
    projectId: 'pets-project-f507e',
    authDomain: 'pets-project-f507e.firebaseapp.com',
    storageBucket: 'pets-project-f507e.appspot.com',
    measurementId: 'G-1C7HXZVQFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKOd4vbWMvEV4Z_MvdDToQffqVGw81YJ0',
    appId: '1:650378069562:android:2404ef86220affc83f1703',
    messagingSenderId: '650378069562',
    projectId: 'pets-project-f507e',
    storageBucket: 'pets-project-f507e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfDgoelMC5Ola0wkCLQ5YEILlb_mQ_jZQ',
    appId: '1:650378069562:ios:998085452367b5b33f1703',
    messagingSenderId: '650378069562',
    projectId: 'pets-project-f507e',
    storageBucket: 'pets-project-f507e.appspot.com',
    androidClientId: '650378069562-cir6medlru0j9skn931lu7ng2e6qsun5.apps.googleusercontent.com',
    iosClientId: '650378069562-fo9cqs7au5n57gd6b8s993f3gk7lkmtp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfDgoelMC5Ola0wkCLQ5YEILlb_mQ_jZQ',
    appId: '1:650378069562:ios:998085452367b5b33f1703',
    messagingSenderId: '650378069562',
    projectId: 'pets-project-f507e',
    storageBucket: 'pets-project-f507e.appspot.com',
    androidClientId: '650378069562-cir6medlru0j9skn931lu7ng2e6qsun5.apps.googleusercontent.com',
    iosClientId: '650378069562-fo9cqs7au5n57gd6b8s993f3gk7lkmtp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
